export const difficultVocabulary = [
  { word: "ambiguous", translation: "คลุมเครือ, กำกวม" },
  { word: "benevolent", translation: "เมตตากรุณา, ใจดี" },
  { word: "cacophony", translation: "เสียงแหลมที่ไม่ไพเราะ" },
  { word: "diligent", translation: "ขยันขันแข็ง, มานะ" },
  { word: "eloquent", translation: "พูดจาคล่องแคล่ว, มีวาทศิลป์" },
  { word: "fastidious", translation: "พิถีพิถัน, เรื่องมาก" },
  { word: "gregarious", translation: "ชอบเข้าสังคม, ชอบอยู่เป็นกลุ่ม" },
  { word: "haphazard", translation: "ไม่เป็นระเบียบ, สะเปะสะปะ" },
  { word: "impetuous", translation: "หุนหันพลันแล่น, วู่วาม" },
  { word: "juxtapose", translation: "วางเคียงข้างกัน, เปรียบเทียบ" },
  { word: "kinetic", translation: "เกี่ยวกับการเคลื่อนไหว" },
  { word: "lethargic", translation: "เฉื่อยชา, เกียจคร้าน" },
  { word: "meticulous", translation: "พิถีพิถัน, ละเอียดรอบคอบ" },
  { word: "nefarious", translation: "ชั่วร้าย, เลวทราม" },
  { word: "oblivious", translation: "ไม่รู้ตัว, ไม่ใส่ใจ" },
  { word: "pernicious", translation: "เป็นอันตราย, ทำลายล้าง" },
  { word: "quintessential", translation: "เป็นแก่นแท้, เป็นตัวอย่างที่ดีที่สุด" },
  { word: "resilient", translation: "ยืดหยุ่น, ฟื้นตัวเร็ว" },
  { word: "surreptitious", translation: "ลับๆ, แอบๆ" },
  { word: "tenacious", translation: "ดื้อรั้น, ไม่ยอมแพ้" },
  { word: "ubiquitous", translation: "มีอยู่ทั่วไป, แพร่หลาย" },
  { word: "verbose", translation: "พูดมาก, เยิ่นเย้อ" },
  { word: "whimsical", translation: "แปลกประหลาด, ไม่แน่นอน" },
  { word: "xenophobia", translation: "ความกลัวหรือเกลียดชังคนต่างชาติ" },
  { word: "yielding", translation: "ยอมแพ���, อ่อนโยน" },
  { word: "zealous", translation: "กระตือรือร้น, มุ่งมั่น" },
  { word: "aberration", translation: "ความผิดปกติ, การเบี่ยงเบน" },
  { word: "brevity", translation: "ความสั้นกระชับ, ความรวบรัด" },
  { word: "cognizant", translation: "รู้, ตระหนัก" },
  { word: "deleterious", translation: "เป็นอันตราย, ทำลาย" },
  { word: "ephemeral", translation: "ชั่วคราว, ไม่ยั่งยืน" },
  { word: "facetious", translation: "ตลกขบขัน, ล้อเล่น" },
  { word: "garrulous", translation: "พูดมาก, ช่างคุย" },
  { word: "hedonistic", translation: "รักความสุข, หมกมุ่นในความสุข" },
  { word: "idiosyncrasy", translation: "ลักษณะเฉพาะตัว, ความแปลก" },
  { word: "judicious", translation: "มีวิจารณญาณ, รอบคอบ" },
  { word: "kaleidoscope", translation: "กล้องตาแมลงวัน, ความหลากหลาย" },
  { word: "labyrinthine", translation: "ซับซ้อน, วกวน" },
  { word: "mellifluous", translation: "ไพเราะ, นุ่มนวล" },
  { word: "nuance", translation: "ความแตกต่างเล็กน้อย, ความละเอียดอ่อน" },
  { word: "ostentatious", translation: "โอ้อวด, ฟุ่มเฟือย" },
  { word: "perfunctory", translation: "ขอไปที, ทำแบบขอให้เสร็จ" },
  { word: "quixotic", translation: "อุดมคติเกินจริง, เพ้อฝัน" },
  { word: "recalcitrant", translation: "ดื้อรั้น, ไม่เชื่อฟัง" },
  { word: "serendipity", translation: "โชคดีที่ได้พบสิ่งดีโดยบังเอิญ" },
  { word: "taciturn", translation: "เงียบขรึม, พูดน้อย" },
  { word: "unequivocal", translation: "ชัดเจน, ไม่คลุมเครือ" },
  { word: "vacillate", translation: "ลังเล, ไม่แน่ใจ" },
  { word: "wistful", translation: "อาลัยอาวรณ์, คิดถึง" },
  { word: "xenial", translation: "เป็นมิตรกับคนแปลกหน้า" },
]
