#!/usr/bin/env python3
"""
Export specific data from SQLite to MySQL compatible SQL
Only export core data tables, skip user-specific data and SQLite internals
"""
import sqlite3
import sys
from pathlib import Path

# Tables to export (skip user-specific tables)
TABLES_TO_EXPORT = [
    'languages',
    'lessons',
    'achievements',
    'badges',
    'challenges',
    'missions',
    'questions',
    'vocabulary',
]

def escape_sql_value(value):
    """Escape SQL values for INSERT statements"""
    if value is None:
        return 'NULL'
    elif isinstance(value, (int, float)):
        return str(value)
    else:
        # Escape single quotes and wrap in quotes
        escaped = str(value).replace("'", "''").replace("\\", "\\\\")
        return f"'{escaped}'"

def export_table_data(cursor, table_name):
    """Export data from a table as MySQL INSERT statements"""
    try:
        # Get column names
        cursor.execute(f"PRAGMA table_info({table_name})")
        columns_info = cursor.fetchall()
        column_names = [col[1] for col in columns_info]
        
        # Get all data
        cursor.execute(f"SELECT * FROM {table_name}")
        rows = cursor.fetchall()
        
        if not rows:
            return f"-- No data in {table_name}\n"
        
        sql_output = f"\n--\n-- Data for table `{table_name}`\n--\n\n"
        
        # Generate REPLACE statements (avoids duplicate key errors)
        for row in rows:
            values = [escape_sql_value(val) for val in row]
            values_str = ', '.join(values)
            sql_output += f"REPLACE INTO `{table_name}` ({', '.join([f'`{col}`' for col in column_names])}) VALUES ({values_str});\n"
        
        return sql_output + "\n"
    
    except Exception as e:
        return f"-- Error exporting {table_name}: {e}\n\n"

def main():
    db_path = Path("data/db.sqlite")
    output_path = Path("database/mysql_data_import.sql")
    
    if not db_path.exists():
        print(f"✗ Error: Database file not found: {db_path}", file=sys.stderr)
        sys.exit(1)
    
    # Connect to SQLite database
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    
    # Start building SQL file
    sql_content = """-- MySQL Data Import from SQLite
-- Database: lingualearn_db
-- Generated by export_sqlite_data.py
-- 
-- This file contains ONLY data INSERTs (no schema)
-- Import this AFTER creating tables with lingualearn.sql

SET FOREIGN_KEY_CHECKS=0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

"""
    
    # Export each table
    print(f"Exporting data from {db_path}...")
    for table_name in TABLES_TO_EXPORT:
        print(f"  • {table_name}...", end=" ")
        table_sql = export_table_data(cursor, table_name)
        sql_content += table_sql
        
        # Count rows
        cursor.execute(f"SELECT COUNT(*) FROM {table_name}")
        row_count = cursor.fetchone()[0]
        print(f"✓ ({row_count} rows)")
    
    # Add footer
    sql_content += """
SET FOREIGN_KEY_CHECKS=1;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
"""
    
    # Write to file
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(sql_content)
    
    conn.close()
    
    print(f"\n✓ Export completed successfully!")
    print(f"  Output: {output_path}")
    print(f"  Size: {len(sql_content):,} characters")
    print(f"\nTo import into MySQL:")
    print(f"  1. First run: mysql -h HOST -P PORT -u USER -pPASSWORD lingualearn_db < database/lingualearn.sql")
    print(f"  2. Then run:  mysql -h HOST -P PORT -u USER -pPASSWORD lingualearn_db < {output_path}")

if __name__ == "__main__":
    main()

